#!/bin/zsh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_PLUGIN_DIR="$REPO_ROOT/plugins/schemaledger"
HOME_PLUGIN_ROOT="$HOME/plugins"
HOME_PLUGIN_DIR="$HOME_PLUGIN_ROOT/schemaledger"
HOME_MARKETPLACE_DIR="$HOME/.agents/plugins"
HOME_MARKETPLACE="$HOME_MARKETPLACE_DIR/marketplace.json"
WORKSPACE_DIR="$REPO_ROOT/workspace"
POSTGRES_DSN="${SCHEMALEDGER_POSTGRES_DSN:-postgresql://postgres:postgres@127.0.0.1:55432/schemaledger_fresh}"
LLM_PROVIDER="${SCHEMALEDGER_LLM_PROVIDER:-lmstudio}"
EMBEDDING_PROVIDER="${SCHEMALEDGER_EMBEDDING_PROVIDER:-$LLM_PROVIDER}"
LM_STUDIO_BASE_URL="${SCHEMALEDGER_LM_STUDIO_BASE_URL:-http://127.0.0.1:1234}"
LM_STUDIO_MODEL="${SCHEMALEDGER_LM_STUDIO_MODEL:-qwen3.5-35b-a3b-uncensored-claude-opus-4.6-affine}"
LM_STUDIO_EMBEDDING_MODEL="${SCHEMALEDGER_LM_STUDIO_EMBEDDING_MODEL:-text-embedding-nomic-embed-text-v1.5}"
OLLAMA_BASE_URL="${SCHEMALEDGER_OLLAMA_BASE_URL:-http://127.0.0.1:11434}"
OLLAMA_MODEL="${SCHEMALEDGER_OLLAMA_MODEL:-}"
OLLAMA_EMBEDDING_MODEL="${SCHEMALEDGER_OLLAMA_EMBEDDING_MODEL:-}"
OPENAI_BASE_URL="${SCHEMALEDGER_OPENAI_BASE_URL:-https://api.openai.com}"
OPENAI_API_KEY="${SCHEMALEDGER_OPENAI_API_KEY:-}"
OPENAI_EMBEDDING_MODEL="${SCHEMALEDGER_OPENAI_EMBEDDING_MODEL:-}"
GEMINI_BASE_URL="${SCHEMALEDGER_GEMINI_BASE_URL:-https://generativelanguage.googleapis.com}"
GEMINI_API_KEY="${SCHEMALEDGER_GEMINI_API_KEY:-}"
GEMINI_EMBEDDING_MODEL="${SCHEMALEDGER_GEMINI_EMBEDDING_MODEL:-}"

mkdir -p "$HOME_PLUGIN_ROOT" "$HOME_MARKETPLACE_DIR"
rm -rf "$HOME_PLUGIN_DIR"
cp -R "$SRC_PLUGIN_DIR" "$HOME_PLUGIN_DIR"

cat > "$HOME_PLUGIN_DIR/.mcp.json" <<EOF
{
  "mcpServers": {
    "schemaledger": {
      "type": "stdio",
      "command": "uv",
      "args": [
        "run",
        "--project",
        "$REPO_ROOT",
        "python",
        "-m",
        "schemaledger.mcp",
        "--workspace",
        "$WORKSPACE_DIR",
        "--dsn",
        "$POSTGRES_DSN"
      ],
      "env": {
        "PYTHONNOUSERSITE": "1",
        "PYTHONPATH": "$REPO_ROOT/src:$REPO_ROOT",
        "SCHEMALEDGER_LLM_PROVIDER": "$LLM_PROVIDER",
        "SCHEMALEDGER_EMBEDDING_PROVIDER": "$EMBEDDING_PROVIDER",
        "SCHEMALEDGER_LM_STUDIO_BASE_URL": "$LM_STUDIO_BASE_URL",
        "SCHEMALEDGER_LM_STUDIO_MODEL": "$LM_STUDIO_MODEL",
        "SCHEMALEDGER_LM_STUDIO_EMBEDDING_MODEL": "$LM_STUDIO_EMBEDDING_MODEL",
        "SCHEMALEDGER_OLLAMA_BASE_URL": "$OLLAMA_BASE_URL",
        "SCHEMALEDGER_OLLAMA_MODEL": "$OLLAMA_MODEL",
        "SCHEMALEDGER_OLLAMA_EMBEDDING_MODEL": "$OLLAMA_EMBEDDING_MODEL",
        "SCHEMALEDGER_OPENAI_BASE_URL": "$OPENAI_BASE_URL",
        "SCHEMALEDGER_OPENAI_API_KEY": "$OPENAI_API_KEY",
        "SCHEMALEDGER_OPENAI_EMBEDDING_MODEL": "$OPENAI_EMBEDDING_MODEL",
        "SCHEMALEDGER_GEMINI_BASE_URL": "$GEMINI_BASE_URL",
        "SCHEMALEDGER_GEMINI_API_KEY": "$GEMINI_API_KEY",
        "SCHEMALEDGER_GEMINI_EMBEDDING_MODEL": "$GEMINI_EMBEDDING_MODEL",
        "SCHEMALEDGER_POSTGRES_DSN": "$POSTGRES_DSN"
      },
      "note": "Home-local SchemaLedger MCP server generated by scripts/install_codex_plugin.sh"
    }
  }
}
EOF

python3 - <<'PY' "$HOME_MARKETPLACE"
import json
import sys
from pathlib import Path

marketplace_path = Path(sys.argv[1])
entry = {
    "name": "schemaledger",
    "source": {
        "source": "local",
        "path": "./plugins/schemaledger",
    },
    "policy": {
        "installation": "AVAILABLE",
        "authentication": "ON_INSTALL",
    },
    "category": "Coding",
}

if marketplace_path.exists():
    data = json.loads(marketplace_path.read_text(encoding="utf-8"))
else:
    data = {
        "name": "local-home-plugins",
        "interface": {"displayName": "Local Home Plugins"},
        "plugins": [],
    }

plugins = [plugin for plugin in data.get("plugins", []) if plugin.get("name") != "schemaledger"]
plugins.append(entry)
data["plugins"] = plugins

if "name" not in data:
    data["name"] = "local-home-plugins"
if "interface" not in data:
    data["interface"] = {"displayName": "Local Home Plugins"}
elif "displayName" not in data["interface"]:
    data["interface"]["displayName"] = "Local Home Plugins"

marketplace_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY

echo "Installed SchemaLedger Codex plugin:"
echo "  plugin: $HOME_PLUGIN_DIR"
echo "  marketplace: $HOME_MARKETPLACE"
echo "  mcp: $HOME_PLUGIN_DIR/.mcp.json"
